version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    #user: "1000:1000"
    container_name: card_analytics_clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client interface
      - "9004:9004"  # MySQL compatibility protocol
      - "9005:9005"  # PostgreSQL compatibility protocol
      - "9009:9009"  # Interserver HTTP port
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./config/clickhouse_config.xml:/etc/clickhouse-server/config.d/custom_config.xml:ro
      - ./database/migrations:/docker-entrypoint-initdb.d:ro
      - clickhouse-logs:/var/log/clickhouse-server
    environment:
      CLICKHOUSE_DB: card_analytics
      CLICKHOUSE_USER: analyst
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    cap_add:
      - SYS_NICE
      - IPC_LOCK
    networks:
      - card_analytics_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: card_analytics_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./reports:/workspace/reports
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: ${JUPYTER_TOKEN}
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: analyst
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - card_analytics_network
    command: start-notebook.sh --NotebookApp.token='${JUPYTER_TOKEN}'

networks:
  card_analytics_network:
    driver: bridge

volumes:
  clickhouse-data:
  clickhouse-logs:
  jupyter_data: